// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajtoemlqvejwhnqwjmrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdG9lbWxxdmVqd2hucXdqbXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzA1MTksImV4cCI6MjA2ODkwNjUxOX0.6TDPLJyfdHxKGoFU_VbtfDU1T76lKOSLk0DoYX_Ruww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});